M #-: Fix rhel7 multipart-post and ruby comp. (#2315)
With multipart-post 2.2.0+:
irb(main):002:0> require 'net/http/post/multipart'
NoMethodError: undefined method `deprecate_constant' for Object:Class