B #-: Fix ldap_auth if group_admin_group_dn is nil (#2403)
As in ruby 2.0
irb(main):001:0> 'a'.casecmp(nil)
TypeError: no implicit conversion of nil into String